#!/bin/bash

# Fail early if there's an issue
set -e

# When .cache files are created, they need to know where HOME is to write there.
# In this case, that should be the HTCondor scratch dir the job is executing in.
export HOME=$(pwd)
echo "HOME is set to: $(pwd)"

# Check if the tar file exists before trying to extract
if [ ! -f snakemake-workflow-env.tar.gz ]; then
    echo "ERROR: snakemake-workflow-env.tar.gz not found!"
    exit 1
fi

# Extract the portable conda environment that was transferred by HTCondor
echo "Extracting conda environment from snakemake-workflow-env.tar.gz..."
tar -xzf "snakemake-workflow-env.tar.gz"

# Activate the conda environment
echo "Activating conda environment"
export PATH=$(pwd)/bin:$PATH
echo "Conda environment activated successfully"

# Now run Snakemake with the activated environment

# The EP will be handed a list of Snakemake arguments
# that were generated by Snakemake at the AP. Those define exactly which step/rule to run
# and with which parameters. Those args must be passed back to Snakemake here to run
# that step.
echo "Starting Snakemake job..."
snakemake "$@"
